"""
agents/pr_agent.py
------------------
Module 5: The PR Agent

Takes an approved ProposedFix and opens a real GitHub pull request:
  1. Forks the upstream repo to GITHUB_USERNAME
  2. Creates a branch named fix/issue-{number}-{slug}
  3. Pushes each fixed file
  4. Opens a PR with a structured description

TEACHING NOTE — When NOT to use an agent (deterministic sequences):

  The PR Agent is NOT an agentic loop. It is a deterministic sequence of
  API calls with a fixed order:

    fork → get_sha → create_branch → push_files → open_pr

  Why not use an agent here? Because:

  1. DETERMINISM: The steps never change based on what we observe. We always
     do them in the same order. An agent shines when it needs to *decide* what
     to do next based on intermediate results. Here there are no decisions.

  2. ERROR HANDLING: With a deterministic sequence, errors are easy to locate.
     "push_file failed on step 3" is clear. With an agent loop, failure can
     occur at any turn, making debugging harder.

  3. COST: Every agent turn costs tokens. A deterministic sequence is free
     (just API calls). Don't pay for intelligence you don't need.

  Rule of thumb:
    Use an agent when: the task requires exploration, reasoning, or dynamic
                       decision-making based on intermediate results
    Use deterministic code when: the steps are fixed and the only question
                                 is "did this API call succeed?"

TEACHING NOTE — Fork-based PR flow for open source:

  The standard open source contribution flow is:
    1. Fork the upstream repo to your own account (so you can push)
    2. Create a feature branch on YOUR fork (not the upstream)
    3. Push commits to your branch
    4. Open a PR from your_fork:your_branch → upstream:main

  This is different from internal team repos where you push directly.
  The GitHub API models this with the "head" field in create_pull:
    head = "your_username:branch_name"
    base = "main"  (on the upstream repo)

TEACHING NOTE — Human-in-the-loop checkpoints:

  Before pushing ANY code, this agent prints the full plan and asks for
  confirmation. This is critical for:

  1. TRUST: Users can verify what will be pushed before it happens
  2. SAFETY: Catches cases where the fix looks wrong on review
  3. COMPLIANCE: Many organisations require human approval before code
     is submitted on their behalf

  Checkpoints are cheap to add and invaluable when things go wrong.
  The cost is one extra input() call. The benefit is catching mistakes
  before they hit a public repo.

TEACHING NOTE — Branch naming conventions:

  We use: fix/issue-{number}-{slug}
    - fix/  prefix signals this is a bugfix branch (vs feat/, docs/, etc.)
    - issue-{number}  links the branch to the GitHub issue number
    - {slug}  a short human-readable description from the fix summary

  This makes branches self-documenting in the GitHub UI.
"""

import re
import sys
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from config.settings import GITHUB_USERNAME
from agents.schemas import ProposedFix, CodeAnalysis
from tools.github import (
    fork_repo,
    create_branch,
    get_file_sha,
    push_file,
    open_pull_request,
    get_default_branch_sha,
)

console = Console()


def _make_slug(text: str, max_len: int = 40) -> str:
    """Turn a sentence into a URL-safe branch slug."""
    slug = text.lower()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug.strip())
    return slug[:max_len].rstrip("-")


def _build_pr_body(
    owner: str,
    repo: str,
    issue_number: int,
    code_analysis: CodeAnalysis,
    proposed_fix: ProposedFix,
) -> str:
    """Build a structured PR description that references the issue and explains the fix."""
    files_list = "\n".join(f"- `{f.path}`: {f.explanation}" for f in proposed_fix.files)
    tests_list = "\n".join(f"- {t}" for t in proposed_fix.test_suggestions)

    caveats_section = ""
    if proposed_fix.caveats and proposed_fix.caveats.strip():
        caveats_section = f"\n## Caveats\n\n{proposed_fix.caveats}\n"

    return f"""Fixes #{issue_number}

## Problem

{code_analysis.issue_summary}

**Root cause:** {code_analysis.root_cause}

## Fix

{proposed_fix.summary}

## Files Changed

{files_list}

## Testing

{tests_list}
{caveats_section}
---
*This PR was generated by [NimbleDev](https://github.com/NimbleDev), a multi-agent AI system.*
*Fix confidence: {proposed_fix.confidence} | Complexity: {code_analysis.estimated_complexity}*
"""


def run(
    owner: str,
    repo: str,
    issue_number: int,
    proposed_fix: ProposedFix,
    code_analysis: CodeAnalysis,
    dry_run: bool = False,
) -> str:
    """
    Open a pull request for the proposed fix.

    Args:
        owner:         Upstream repo owner (e.g. 'psf')
        repo:          Repo name (e.g. 'requests')
        issue_number:  GitHub issue number
        proposed_fix:  The approved ProposedFix from Fix Writer
        code_analysis: The CodeAnalysis for PR description context
        dry_run:       If True, print the plan but don't execute

    Returns:
        URL of the opened PR (or dry-run summary)
    """
    fork_owner = GITHUB_USERNAME
    branch_slug = _make_slug(proposed_fix.summary)
    branch_name = f"fix/issue-{issue_number}-{branch_slug}"

    # ── Human-in-the-loop checkpoint ──────────────────────────────────────────
    # Print the full plan before touching anything.

    plan_table = Table(title="PR Plan", show_header=True, header_style="bold cyan")
    plan_table.add_column("Step", style="dim")
    plan_table.add_column("Action")
    plan_table.add_row("1", f"Fork [cyan]{owner}/{repo}[/cyan] → [cyan]{fork_owner}/{repo}[/cyan]")
    plan_table.add_row("2", f"Create branch [cyan]{branch_name}[/cyan]")
    for i, f in enumerate(proposed_fix.files, 3):
        plan_table.add_row(str(i), f"Push [cyan]{f.path}[/cyan]")
    plan_table.add_row(
        str(len(proposed_fix.files) + 3),
        f"Open PR: [cyan]{owner}/{repo}[/cyan] ← [cyan]{fork_owner}:{branch_name}[/cyan]"
    )

    console.print(Panel(
        f"[bold]PR Agent — Ready to Submit[/bold]\n"
        f"Issue: [cyan]{owner}/{repo}#{issue_number}[/cyan]\n"
        f"Fix: {proposed_fix.summary[:80]}",
        border_style="yellow"
    ))
    console.print(plan_table)

    if dry_run:
        console.print("\n[yellow]DRY RUN — no changes made.[/yellow]")
        return f"(dry run) Would open PR on {owner}/{repo} from {fork_owner}:{branch_name}"

    console.print(
        "\n[bold yellow]This will fork the repo and open a real GitHub PR.[/bold yellow]\n"
        "Type [bold]yes[/bold] to continue, or anything else to cancel: ",
        end="",
    )
    try:
        answer = input().strip().lower()
    except (EOFError, KeyboardInterrupt):
        answer = ""

    if answer != "yes":
        console.print("[red]Cancelled.[/red]")
        sys.exit(0)

    # ── Step 1: Fork the repo ──────────────────────────────────────────────────
    console.print("\n[bold cyan]Step 1:[/bold cyan] Forking repo...")
    fork_result = fork_repo(owner, repo)
    console.print(f"  [dim]{fork_result}[/dim]")

    # GitHub forks are async — give it a moment
    import time
    time.sleep(3)

    # ── Step 2: Get base SHA ───────────────────────────────────────────────────
    console.print("\n[bold cyan]Step 2:[/bold cyan] Getting default branch SHA...")
    sha_result = get_default_branch_sha(fork_owner, repo)
    if sha_result.startswith("Error"):
        # Try upstream if fork isn't ready yet
        sha_result = get_default_branch_sha(owner, repo)
    # sha_result is "abc1234 (branch: main)" — extract just the SHA
    base_sha = sha_result.split()[0]
    default_branch = sha_result.split("branch: ")[-1].rstrip(")")
    console.print(f"  [dim]Base SHA: {base_sha[:7]} on {default_branch}[/dim]")

    # ── Step 3: Create branch ──────────────────────────────────────────────────
    console.print(f"\n[bold cyan]Step 3:[/bold cyan] Creating branch [cyan]{branch_name}[/cyan]...")
    branch_result = create_branch(fork_owner, repo, branch_name, base_sha)
    console.print(f"  [dim]{branch_result}[/dim]")

    # ── Step 4: Push each file ─────────────────────────────────────────────────
    console.print(f"\n[bold cyan]Step 4:[/bold cyan] Pushing {len(proposed_fix.files)} file(s)...")
    for fixed_file in proposed_fix.files:
        console.print(f"  [yellow]→[/yellow] Pushing [cyan]{fixed_file.path}[/cyan]...")

        # Get existing SHA (needed to update an existing file)
        existing_sha = get_file_sha(fork_owner, repo, fixed_file.path, branch_name)
        if existing_sha.startswith("Error"):
            existing_sha = get_file_sha(fork_owner, repo, fixed_file.path, default_branch)

        commit_msg = f"fix: {fixed_file.explanation[:72]}"
        push_result = push_file(
            owner=fork_owner,
            repo=repo,
            path=fixed_file.path,
            content=fixed_file.fixed_content,
            message=commit_msg,
            branch=branch_name,
            sha=existing_sha,
        )
        console.print(f"  [dim]{push_result}[/dim]")

    # ── Step 5: Open the PR ────────────────────────────────────────────────────
    console.print(f"\n[bold cyan]Step 5:[/bold cyan] Opening PR on [cyan]{owner}/{repo}[/cyan]...")
    pr_title = f"fix: {proposed_fix.summary[:72]} (closes #{issue_number})"
    pr_body = _build_pr_body(owner, repo, issue_number, code_analysis, proposed_fix)
    pr_head = f"{fork_owner}:{branch_name}"

    pr_result = open_pull_request(
        owner=owner,
        repo=repo,
        title=pr_title,
        body=pr_body,
        head=pr_head,
        base=default_branch,
    )
    console.print(f"\n{pr_result}")

    # Extract URL from result string for return value
    for line in pr_result.splitlines():
        if line.startswith("URL:"):
            return line.split("URL:", 1)[1].strip()
    return pr_result
